### ISSUE TITLE
attribute types definitions and top level class names clashes.

### ISSUE THREAD

**Issue by codesnik** [solnic/virtus#234]
This is a quite subtle problem. I'll try to illustrate:

``` ruby
require 'virtus'
require 'mongoid'
class Foo
  include Virtus.model
  attribute :bar, Boolean
end
Foo.new(bar: 1).bar # => 1
```

Mongoid defines it's own ::Boolean class, and that was enough to silently break coercer.

This is probably a mongoid problem, it's quite dirty. But it raises a question if attribute type declaration magic is magic enough. Thoughts?

**Comment by borama** [comment]
@solnic I think that the documentation in the README, that was [added](https://github.com/solnic/virtus/commit/d238b7e76f4baedf28a207e0c13b1ab902ce20a5) when closing this PR, is actually wrong.

Here, @acook says to use the `Virtus::Attribute::Boolean` class for explicitly specifying the `Boolean` type but in the [README](https://github.com/solnic/virtus/blob/master/README.md#important-note-about-boolean-type) there is `Axiom::Types::Boolean` suggested. I believe that this causes problems that are described in this [StackOverflow question](http://stackoverflow.com/questions/43977071/use-boolean-attribute-helper-methods-when-extending-from-virtus-model-on-the-fly/43988357#43988357), which seem to be fixed by using the `Virtus::Attribute::Boolean` class indeed.

Can you confirm the correct form, please?

**Comment by solnic** [comment]
Sorry, I no longer maintain virtus.
